development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV("REDIS_URL") %>
  channel_prefix: Slackr_production
#change the production url to heroku thingy
#{ "redis://localhost:6379/1" }
